#!/usr/bin/env bash

main() {
  local opt OPTARG OPTIND
  while getopts "u:h" opt; do
    case $opt in
    u) echo " $opt was passed $OPTARG" ;;
    h) echo "$0"
       echo "================="
       echo "-u <Username>"
       echo "-h This Help"
       echo "=================" ;;
    \?) echo "Invalid Option" ;;
    :) echo "Option $OPTARG requires argument" ;;
    esac
  done
}

main
